import turtle

tim = turtle.Turtle()

tim.color("red")
tim.penup()
tim.goto(-75, -75)
tim.pendown()
tim.begin_fill()
tim.circle(150)
tim.end_fill()
tim.color("white")
tim.penup()
tim.left(90)
tim.forward(70)
tim.right(90)
tim.pendown()
tim.begin_fill()
tim.circle(80)
tim.end_fill()
tim.color("red")
tim.penup()
tim.left(90)
tim.forward(40)
tim.right(90)
tim.pendown()
tim.begin_fill()
tim.circle(40, 630)
tim.end_fill()
tim.color("white")
tim.begin_fill()
tim.left(180)
tim.forward(145)
tim.right(180)
tim.forward(146)
tim.circle(40, 90)
tim.right(90)
tim.forward(40)
tim.right(90)
tim.circle(-80, 90)
tim.forward(145)
tim.right(90)
tim.forward(39)

tim.end_fill()


turtle.done()
